-- SQLite
-- SQLite
--create view   CalendarTimeSheet as
SELECT
    CALENDARDATE,
    STRFTIME('%Y-%m-%d %H:%M:%S',
    DATETIME(CALENDARDATE/1000,
    'unixepoch'))AS DXTX,
    WEEKDAYNAME,
    YEAR,
    MONTH,
    CASE
        WHEN V.CHARGEABLEDAY>0 THEN
            CHARGEABLEDAY
        ELSE
            0
    END           AS VACATIONCHARGABLE,
    CASE
        WHEN PH.SUMMARY IS NULL THEN
            0
        ELSE
            1
    END           AS PUBLICHOLIDAYCHARGABLE,
    PH.SUMMARY,
    V.LEAVEREQUESTID
FROM
    CALENDARMASTER   C
    LEFT JOIN CALENDARVACATION V
    ON V.VACATIONDATE = C.CALENDARDATE
    LEFT JOIN PUBLICHOLIDAY PH
    ON PH.ENDDATE = C.CALENDARDATE